
server:
  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  instance:
    hostname: eureka-0.eureka
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_DEFAULTZONE_URL:http://localhost:8761/eureka}
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000

EUREKA_DEFAULTZONE_URL: http://eureka-0.eureka:8761/eureka/




