
server:
  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_DEFAULTZONE_URL:http://localhost:8761/eureka}
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 9000

EUREKA_DEFAULTZONE_URL: http://${eureka.instance.hostname}:8761/eureka


    