
server:
  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  instance:
    hostname: ${POD_NAME}.eureka
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULTZONE_URL:http://localhost:8761/eureka}
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 7000

EUREKA_DEFAULTZONE_URL: http://${POD_NAME}.eureka:8761/eureka/




