apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: discovery-service
spec:
  selector:
    matchLabels:
      app: discovery-service
  serviceName: discovery-service
  replicas: 2
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
      - name: discovery-service
        image: princeabhijeet/discovery-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8761
