apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
spec:
  selector:
    matchLabels:
      app: eureka
  serviceName: eureka
  replicas: 3
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: princeabhijeet/discovery-service
        ports:
        - containerPort: 8761
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        
        